github:
  - alexgorbatchev
  - JounQin
  - 1stG
  - rx-ts
  - un-ts
open_collective: unts
patreon: 1stG
custom:
  - https://opencollective.com/1stG
  - https://opencollective.com/rxts
  - https://afdian.net/@JounQin
